### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#15]
近期：（V2.5.4？）
* [x] 15x15的样板版本
* [x] 公共事件
* [x] 支持多重装备（一个装备可以装到多个孔上）
* [x] 工具栏按钮增添至8个，快捷商店和虚拟键盘同时显示
* [x] 等待事件提供flag:px和flag:py在0~415之间
* [x] 事件：呼出存档界面；呼出怪物手册
* [x] 事件：使用道具，暂停bgm，停止所有se
* [x] 独立开关
* [x] 颜色选择器内嵌到事件图块中
* [x] localStorage存哪些存档位有占用，提供core.hasSave()这个API
* [x] 地图编辑器表格的重构
* [x] 各个辅助小工具的优化
* [x] 优化自动存档的性能
* [x] 等待事件可被Ctrl（长按）跳过

远期：
* [ ] 树状存档？
* [ ] 尝试转向WebGL？

**Comment by zhaouv** [comment]
更长期:(after全GUI操作),在魔塔服务器上做塔,全部数据储存在数据库

**Comment by zhaouv** [comment]
播放录像的实现思路:    
core中每实际生效一个行动,就调函数    
```
core.achieve(action);    
```
`action`属于`['up','down','left','down','turn','usefly','usebomb','choice|1','choice|2',...]`    
播放录像时
```
replayActionList.forEach(function(action,index){
    doaction
    while(core.achieve中已完成的action!==index)
    {间隔0.1秒;doaction;达到一定失败次数后判定录像无效;}
});
```

**Comment by zhaouv** [comment]
短期:一键生成发布版    
写一个`release.cmd`或者给`启动服务.exe`多一个按钮:   
+ 创建一个目录release或者是和塔的id同名    
+ 自动把js压缩成.min.js    
+ 把`index.html` `main.js` `styles.css` `libs/*.min.js` `images下第一层的图片(不包括常用素材那个目录)` `sounds/` 扔进去    
+ 未来可以在设置好发布者id后一键上传(更新)到服务器

(虽然说全一块挂网上也只有那些文件会被加载吧,,,)

**Comment by zhaouv** [comment]
2.1.2 blockly  
+ [ ] 坐标允许flag (hide show的多事件除外)  
+ [ ] 商店图块

**Comment by zhaouv** [comment]
+ [ ] airwall: 数字17, 放在在清除块下方  
+ [ ] 笔刷的新模式: 把tilesets中的东西以矩形区域的方式画上去
