### ISSUE TITLE
V2.0 To-Do List

### ISSUE THREAD

**Issue by ckcz123** [ckcz123/mota-js#57]
在此列出所有2.0版本发布前要完成的工作，做完一个勾一个。

全部做完即可正式发v2.0版本。

**Comment by zhaouv** [comment]
# editor  
+ 前端上实现模式切换  

+ [ ] 通过tabs或下拉菜单切换模式,现在展开在下面的6-7个框一次只显示一个

+ blockly
+ [ ] 改为弹窗的形式
+ [ ] 编辑多行文本用的对话框,改成弹窗的形式

+ 脚本编辑器

+ [ ] 能够编辑 project 里的函数
+ [ ] 同用多行文本编辑的对话框

+ 不是必要但是很值得2.0添加的内容

> + [ ] 给事件增加类似无id的红标的绿色标记放在该图块右下,大概占1/9面积  
> + [ ] 事件复制,以及能通过中间的地图来在右边选中图块
> + [ ] 有些修改需要刷新浏览器来生效

**Comment by zhaouv** [comment]
# 运行时
+ [ ] 48x32的素材支持  
创建 npc48 和 monster48 两个cls

+ [ ] 录像存储机制
录像对于道具使用和商店记录全ID

**Comment by ckcz123** [comment]
# 关于index.html的处理
+ [ ] startBackground的src可以在projects中指定
并建议使用jpg格式以压缩背景图空间

+ [ ] startLogo的style，包括color和display可在projects中指定
用户可选标题颜色，也可以隐藏标题（如果背景图自带）

+ [ ] 难度分歧选择在projects中指定
* ID固定用四个：easyLevel, normalLevel, hardLevel, hellLevel
* 用户可以在projects中指定哪些显示哪些不显示
* 用户可以编辑每个ID对应的难度中文名（如“简单”）和难度英文名（如"Easy"）；默认为 `简单-Easy`, `普通-Normal`, `困难-Hard`, `噩梦-Hell`
* 可以直接在写死main.js的onclick中写死四个ID的点击事件，`core.events.startGame('Hard');`的参数以用户设置的为准；也可以运行时通过for循环来动态添加onclick事件

**Comment by ckcz123** [comment]
#60 

+ [ ] core文件的分解
根据需求拆分成多个文件

+ [ ] 动态加载的解耦合
在几个文件内不再使用`main.instance.xxx`，而是利用`eval`在`function xxx()`中初始化。

**Comment by ckcz123** [comment]
## 各种工具的重新支持

+ [ ] 地图生成器
需要添加48x32的素材支持

+ [ ] 便捷PS工具
需要添加48x32的支持
对于不是标准的尺寸自动调整为标准

+ [ ] JS代码压缩工具

+ [ ] RM动画导出器

**Comment by ckcz123** [comment]
## editor
+ [ ] 怪物的属性使用extra来进行拓展
extra写上其他所有可能的特殊，比如领域的extra就是`"value": 100, "range": 2, "zoneSquare": false`，这样也不会再考虑无关属性和null的问题

+ [ ] 新增图块的样式
添加素材需要用显眼的颜色；添加ID需要用Button
如果可以尽量自动刷新，很难或做不到就算了...

+ [ ] 列表的支持
levelChooseButtons，shops，levelUp都需要使用弹窗的列表来处理
像全塔属性的floorIds，pngs，pngs等最好也需要列表，不然不太方便

+ [ ] 输入框下面给出“编辑”按钮，点击可以进入实际的编辑框
建议能用的全部都用上（毕竟textarea太丑了...），包括itemEffect那些

其他的想到再加...

**Comment by ckcz123** [comment]
+ [ ] 清空存档可选择只清空当前塔和全部塔

**Comment by zhaouv** [comment]
怪物最下面加一栏添加新属性
![image](https://user-images.githubusercontent.com/26158289/37240963-25525574-248d-11e8-8709-84615648bd46.png)

**Comment by i2Echo** [comment]
## 关于所有可枚举配置项的一个想法：
分为两个部分，一个为default.setting，一个为user.setting，default配置文件包含所有可枚举配置项并给定默认值（注释标明可选值），user配置文件只添加用户修改的配置；这样可以尽量少的让用户去配置，降低难度；读取配置的时候都一律先读user配置，出错或没找到再读default配置，保证不出错。
至于编辑这个配置文件，不管是高能力用户（直接修改配置）还是小白用户（利用图形化修改再写入）都是比较有好的。

**Comment by ckcz123** [comment]
## 需要进一步完善的部分

+ [ ] 道具使用效果的分离
useItem函数和canUseItem函数提出来

+ [ ] 地图图块属性的显示
对于terrains和animates，在“图块属性”中显示`noPass`和`trigger`两项，可编辑

+ [ ] 事件编辑器退出后有一定概率会让文本留在界面上，需修复

+ [ ] 事件编辑器和文本编辑器之间的Bar可拖动（即可以拉大代码框高度）
